backend:
  name: git-gateway
  branch: master
media_folder: src/public/uploads
public_folder: /uploads
collections:
  -
    label: 'YksittÃ¤iset sivut'
    name: pages
    editor:
      preview: false
    files:

      -  
        name: coverPage
        label: 'Cover page'
        file: src/data/slides/coverPage.json
        format: json
        fields:
          -
            label: Unique id
            hint: "Jokin sisÃ¤ltÃ¶Ã¤ kuvaava nimi, jolla sen erottaa muista" 
            name: id
            widget: string
            required: true
          -
            label: 'Desktop background image'
            name: desktopSrc
            widget: image
          -
            label: 'Mobile background image'
            name: src
            widget: image
          -
            label: Header ğŸ‡«ğŸ‡®
            name: header1
            widget: string
          -
            label: Ã„LÃ„ MUUTA
            hint: "Ã„lÃ¤ muuta, pidÃ¤ sisÃ¤ltÃ¶nÃ¤ aina \"cover\"" 
            name: type
            widget: string
            default: cover
          -
            label: Subheader ğŸ‡«ğŸ‡®
            name: subheader
            widget: string
          -
            label: Header ğŸ‡¬ğŸ‡§English
            name: header1_eng
            widget: string
          -
            label: Subheader ğŸ‡¬ğŸ‡§ English
            name: subheader_eng
            widget: string
      -
        name: finalPage
        label: 'Final page'
        file: src/data/slides/finalPage.json
        format: json
        fields:
          -
            label: Unique id
            hint: "Jokin sisÃ¤ltÃ¶Ã¤ kuvaava nimi, jolla sen erottaa muista" 
            name: id
            widget: string
            required: true
          -
            label: Ã„LÃ„ MUUTA
            hint: "Ã„lÃ¤ muuta, pidÃ¤ sisÃ¤ltÃ¶nÃ¤ aina \"finalPage\"" 
            name: type
            widget: hidden
            default: finalPage
          -
            label: 'Areena video id'
            name: areenaVideo
            widget: string
      -
        name: credits1
        label: 'Credits 1/2'
        file: src/data/slides/credits1.json
        format: json
        fields:
          -
            label: Unique id
            hint: "Jokin sisÃ¤ltÃ¶Ã¤ kuvaava nimi, jolla sen erottaa muista" 
            name: id
            widget: string
            required: true
          -
            label: Ã„LÃ„ MUUTA
            hint: "Ã„lÃ¤ muuta, pidÃ¤ sisÃ¤ltÃ¶nÃ¤ aina \"text\"" 
            name: type
            widget: hidden
            default: "text"
            required: true
          -
            label:  Ã„LÃ„ MUUTA
            hint: "Ã„lÃ¤ muuta, pidÃ¤ aina on-asennossa"
            name: credits
            widget: hidden
            default: true
            required: true
          -
            label: Krediitit
            hint: "Kirjoita krediitit. Krediittisivuja varattu 2."
            name: text
            widget: markdown
          -
            label: Krediitit ğŸ‡¬ğŸ‡§ English
            hint: "Kirjoita krediitit. Krediittisivuja varattu 2."
            name: text_eng
            widget: markdown
      -
        name: credits2
        label: 'Credits 2/2'
        file: src/data/slides/credits2.json
        format: json
        fields:
          -
            label: Unique id
            hint: "Jokin sisÃ¤ltÃ¶Ã¤ kuvaava nimi, jolla sen erottaa muista" 
            name: id
            widget: string
            required: true
          -
            label: Ã„LÃ„ MUUTA
            hint: "Ã„lÃ¤ muuta, pidÃ¤ sisÃ¤ltÃ¶nÃ¤ aina \"text\"" 
            name: type
            widget: string
            default: text
          -
            label:  Ã„LÃ„ MUUTA
            hint: "Ã„lÃ¤ muuta, pidÃ¤ aina on-asennossa"
            name: credits
            widget: boolean
            default: true
          -
            label: Text
            hint: "Kirjoita krediitit. Krediittisivuja varattu 2."
            name: text
            widget: markdown
          -
            label: Krediitit ğŸ‡¬ğŸ‡§ English
            hint: "Kirjoita krediitit. Krediittisivuja varattu 2."
            name: text_eng
            widget: markdown
  -
    label: 'Video background slides'
    identifier_field: id
    name: video-bg-slides
    folder: src/data/slides
    editor:
      preview: false
    create: true
    format: json
    filter:
      field: type
      value: background-video
    fields:
      -
        label: 'An unique identifier'
        name: id
        widget: string
      -
        label: Type
        name: type
        widget: hidden
        default: background-video
      -
        label: 'ğŸ“±MOBILE Background video'
        name: src
        widget: file
      -
        label: 'ğŸ–¥ï¸DESKTOP Background video'
        name: src_desktop
        widget: file
      -
        label: 'Bottom positioned text'
        name: bottom
        widget: boolean
        default: false
      - 
        label: "Text location"
        name: "text_location"
        widget: "select"
        options:
          - { label: "1", value: "0" }
          - { label: "2", value: "1" }
          - { label: "3", value: "2" }
          - { label: "4", value: "3" }
          - { label: "5", value: "4" }
          - { label: "6", value: "5" }
          - { label: "7", value: "6" }
          - { label: "8", value: "7" }
          - { label: "9", value: "8" }
      -
        label: Text
        name: text
        widget: markdown
      -
        label: Text ğŸ‡¬ğŸ‡§ English 
        name: text_eng
        widget: markdown
  -
    label: 'Still background slides'
    identifier_field: id
    name: still-bg-slides
    folder: src/data/slides
    format: json
    editor:
      preview: false
    create: true
    filter:
      field: type
      value: still
    fields:
      -
        label: 'An unique identifier'
        name: id
        widget: string
      -
        label: Type
        name: type
        widget: hidden
        default: still
      -
        label: 'Bottom positioned text'
        name: bottom
        widget: boolean
        default: true
      -
        label: 'Background image'
        name: src
        widget: image
      -
        label: Text
        name: text
        widget: markdown
      -
        label: Text ğŸ‡¬ğŸ‡§ English 
        name: text_eng
        widget: markdown
  -
    label: 'Graph slides'
    identifier_field: id
    name: graph-slides
    folder: src/data/slides
    format: json
    editor:
      preview: false
    create: true
    filter:
      field: type
      value: graph
    fields:
      -
        label: 'An unique identifier'
        name: id
        widget: string
      -
        label: Type
        name: type
        widget: hidden
        default: graph
      -
        label: 'Image desktop'
        name: src
        widget: image
      -
        label: 'Image mobile'
        name: src_mobile
        widget: image
        required: false
      -
        label: 'Image desktop ğŸ‡¬ğŸ‡§ English'
        name: src_eng
        widget: image
      -
        label: 'Image mobile ğŸ‡¬ğŸ‡§ English'
        name: src_mobile_eng
        widget: image
        required: false
  -
    label: 'Subtitled video slides'
    name: sub-video-slides
    folder: src/data/slides
    identifier_field: id
    format: json
    editor:
      preview: false
    create: true
    filter:
      field: type
      value: subtitled-video
    fields:
      -
        label: Type
        name: type
        widget: hidden
        default: subtitled-video
      -
        label: 'An unique identifier'
        name: id
        widget: string
      -
        label: ğŸ“±MOBILE Video
        name: src
        widget: file
      -
        label: ğŸ–¥ï¸ DESKTOP Video
        name: src_desktop
        widget: file
      -
        label: 'Subtitle (*.vtt file)'
        name: sub
        widget: file
        required: false
      -
        label: 'Tg name'
        name: tg_name
        widget: string
        required: false
      -
        label: 'Tg title'
        name: tg_title
        widget: string
        required: false
      -
        label: 'Subtitle (*.vtt file) ğŸ‡¬ğŸ‡§ English'
        name: sub_eng
        widget: file
        required: false
      -
        label: 'Tg name ğŸ‡¬ğŸ‡§ English'
        name: tg_name_eng
        widget: string
        required: false
      -
        label: 'Tg title ğŸ‡¬ğŸ‡§ English'
        name: tg_title_eng
        widget: string
        required: false
  -
    label: 'Plain text slides'
    identifier_field: id
    name: plain-text-slides
    folder: src/data/slides
    format: json
    create: true
    editor:
      preview: false
    filter:
      field: plaintext
      value: true
    fields:
      -
        label: 'An unique identifier'
        name: id
        widget: string
      -
        label: Type
        name: type
        widget: hidden
        default: text
      -
        label: Plaintext
        name: plaintext
        widget: hidden
        default: true
      -
        label: Text
        name: text
        widget: markdown
      -
        label: Text ğŸ‡¬ğŸ‡§ English
        name: text_eng
        widget: markdown
  -
    label: 'All slides'
    name: all-slides
    folder: src/data/slides
    identifier_field: id
    format: json
    create: false
    fields:    
      -
        label: Text
        name: text
        widget: markdown
  -
    name: settings
    label: NÃ¤kymÃ¤
    files:
      -
        name: collectionOrder
        format: json
        label: Muuta jÃ¤rjestystÃ¤
        file: src/data/displayOrder.json
        fields:
          -
            label: SisÃ¤llÃ¶t
            name: data
            widget: list
            fields:
              -
                label: 'SisÃ¤llÃ¶n id'
                name: collectionName
                widget: relation
                collection: all-slides
                searchFields:
                  - id
                valueField: id